export const USER_LOGIN = 'GIRLS_SPORT_NEWS/USER_LOGIN';

export const AUTH_PENDING = 'GIRLS_SPORT_NEWS/AUTH_PENDING';
export const AUTH_SUCCESS = 'GIRLS_SPORT_NEWS/AUTH_SUCCESS';
export const AUTH_FAILURE = 'GIRLS_SPORT_NEWS/AUTH_FAILURE';
